name: Build and Deploy Documentation

on:
  push:
    branches:
      - 4_build_docs_ci
  workflow_dispatch:

jobs:
  build_docs:
    name: Build Mesh Adaptation Documentation
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mesh-adaptation/firedrake-parmmg:latest
      options: --user root
      volumes:
        - ${{ github.workspace }}:/home/firedrake/output
    steps:
      - uses: actions/checkout@v3

      - name: Install requirements
        run: |
          . /home/firedrake/firedrake/bin/activate
          python3 -m pip install -r requirements.txt
          cd /home/firedrake/firedrake/src/
          git clone https://github.com/mesh-adaptation/UM2N.git
          python3 -m pip install -e UM2N
        working-directory: /home/firedrake/output/
        shell: bash

      - name: Build HTML Documentation
        run: |
          . /home/firedrake/firedrake/bin/activate
          cd docs
          # make run_animate_demos
          # make run_goalie_demos
          # make run_movement_demos
          make html
        working-directory: /home/firedrake/output/
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: /home/firedrake/output/docs/build/html

  deploy:
    name: Deploy to GitHub Pages
    needs: build_docs
    if: ${{ github.ref == 'refs/heads/4_build_docs_ci' }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://mesh-adaptation.github.io/test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4