name: 'Build bespoke Firedrake Docker container'

on:
  # Build the Docker container if the PETSc one builds successfully
  workflow_run:
    workflows: ['Build bespoke PETSc Docker container']
    types:
      - completed

  # Build the Docker container every Saturday at 1AM
  schedule:
    - cron: '0 1 * * 6'

jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: 'Build Docker container'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out the repo'
        id: checkout
        uses: actions/checkout@v4

      - name: 'Determine files differing from target branch'
        if: ${{ !( github.event_name == 'schedule') }}
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            .github/workflows/docker.yml
            .github/workflows/Dockerfile.firedrake

      - name: 'Set up Docker buildx'
        id: buildx
        if: ${{ (steps.changed-files.outputs.any_changed == 'true') || ( github.event_name == 'schedule') }}
        uses: docker/setup-buildx-action@v3

      - name: 'Log into GitHub Container Repository'
        id: login
        if: ${{ (steps.changed-files.outputs.any_changed == 'true') || ( github.event_name == 'schedule') }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: 'Build Firedrake container and push to GitHub Container Repository'
        id: build-and-push
        if: ${{ (steps.changed-files.outputs.any_changed == 'true') || ( github.event_name == 'schedule') }}
        uses: docker/build-push-action@v5
        with:
          push: true
          no-cache: true
          file: docker/Dockerfile.firedrake
          tags: ghcr.io/mesh-adaptation/firedrake-parmmg:latest
