name: 'Build bespoke PETSc Docker container'

on:
  # Check that Docker build succeeds when these files get changed in an open PR
  pull_request:
    paths:
      - '.github/workflows/docker_petsc-parmmg.yml'
      - 'docker/Dockerfile.petsc'

  # Build and push the Docker container when these files get changed on the main branch
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docker_petsc-parmmg.yml'
      - 'docker/Dockerfile.petsc'

  # Build and push the Docker container every Saturday at 1AM
  schedule:
    - cron: '0 1 * * 6'

  # Manually trigger the workflow
  workflow_dispatch:

jobs:
  docker:
    uses: ./.github/workflows/reusable_docker_build.yml
    with:
      dockerfile-path: 'docker/Dockerfile.petsc'
      docker-image-tag: 'ghcr.io/mesh-adaptation/petsc-parmmg:latest'