name: 'Reusable Test Suite'

on:
  workflow_call:
    inputs:
      docker-image:
        description: 'Name of the Firedrake Docker image to use'
        required: false
        default: 'firedrake-parmmg'
        type: string
      test-command:
        description: 'Command to run before running tests'
        required: false
        type: string

# Cancel jobs running if new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test_suite:
    name: 'Test suite'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mesh-adaptation/${{ inputs.docker-image }}:latest
      options: --user root

    steps:
      - name: 'Check out the repo'
        id: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 'Install package'
        run: |
          . /home/firedrake/firedrake/bin/activate
          git config --global --add safe.directory '*'
          make install_dev

      - name: 'Lint'
        run: |
          . /home/firedrake/firedrake/bin/activate
          make lint

      - name: 'Run tests'
        run: |
          . /home/firedrake/firedrake/bin/activate
          ${{ inputs.test-command }}
          python $(which firedrake-clean)
          python -m coverage erase
          python -m coverage run --source=${{ github.event.repository.name }} -m pytest -v --durations=20 test
          python -m coverage report -m
