name: 'Reusable Test Suite'

on:
  workflow_call:
    inputs:
      docker-image:
        description: 'Name of the Firedrake Docker image to use'
        required: false
        default: 'firedrake-parmmg'
        type: string

# Cancel jobs running if new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test_suite:
    name: 'Test suite'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mesh-adaptation/${{ inputs.docker-image }}:latest
      options: --user root

    steps:
      - name: 'Check out the repo'
        id: checkout
        uses: actions/checkout@v4

      - name: 'Lint'
        run: |
          . /home/firedrake/firedrake/bin/activate
          make lint

      - name: 'Run tests'
        run: |
          . /home/firedrake/firedrake/bin/activate
          python -m coverage run --source=${{ github.repository }} -m pytest -v --durations=20 test && python -m coverage report
